# Generated by Django 5.0.8 on 2024-08-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_check_in_time_employee_check_out_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_absent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
