# Generated by Django 5.0.8 on 2024-08-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], default='Day', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='total_work_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
