# Generated by Django 5.0.8 on 2024-08-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='total_work_hours',
        ),
    ]
