# Generated by Django 5.0.8 on 2024-08-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendancerecord_total_work_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
