# Generated by Django 5.0.8 on 2024-08-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_delete_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
